Disables compression and changed the logic to sue shallow clone

diff --git a/.github/workflows/nc-fork.yaml b/.github/workflows/nc-fork.yaml
--- a/.github/workflows/nc-fork.yaml
+++ b/.github/workflows/nc-fork.yaml
@@ -22,6 +22,7 @@ jobs:
         run: |
           git config --global http.postBuffer 524288000
           git config --global http.maxRequestBuffer 1048576000
+          git config --global core.compression 0 # Disables compression
           
       - name: Fork NextCloud Repository Master Branch Only
         env:
@@ -29,7 +30,11 @@ jobs:
         run: |
           retries=0
           while [ $retries -lt 5 ]; do
-            git clone --single-branch --branch master https://github.com/nextcloud/server.git && break || sleep 15
+            # Use shallow clone to reduce data transfer and continue on errors, logging outputs
+            git clone --depth=1 --no-single-branch --branch master https://github.com/nextcloud/server.git && break || {
+              echo "Failed to clone, retrying..."
+              sleep 15
+            }
             retries=$((retries + 1))
           done
           if [ $retries -eq 5 ]; then
